apiVersion: nova.openstack.org/v1beta1
kind: Nova
metadata:
  name: nova
spec:
  secret: osp-secret
  metadataServiceTemplate:
    enabled: false
  cellTemplates:
    cell0:
      cellDatabaseAccount: nova-cell0
      hasAPIAccess: true
    cell1:
      cellDatabaseAccount: nova-cell1
      conductorServiceTemplate:
        replicas: 1
      hasAPIAccess: true
      metadataServiceTemplate:
        enabled: true
