apiVersion: nova.openstack.org/v1beta1
kind: NovaConductor
metadata:
  name: novaconductor-sample
spec:
  cellName: cell1
  containerImage: quay.io/podified-antelope-centos9/openstack-nova-conductor:current-podified
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  secret: osp-secret
  serviceAccount: nova
