---
- name: Kustomize ControlPlane
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Ensure the kustomizations dir exists
      ansible.builtin.file:
        path: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane"
        state: directory

    - name: Create kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/71-controlplane-kustomization.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          namespace: {{ cifmw_install_yamls_defaults['NAMESPACE'] }}
          patches:
          - target:
              kind: OpenStackControlPlane
            patch: |-
              - op: replace
                path: /spec/nova/template/apiServiceTemplate/replicas
                value: 2

              - op: replace
                path: /spec/neutron/template/replicas
                value: 2

              - op: replace
                path: /spec/neutron/template/customServiceConfig
                value: |
                  [DEFAULT]
                  debug = True

              - op: replace
                path: /spec/ovn/template/ovnDBCluster/ovndbcluster-nb/replicas
                value: 2

              - op: replace
                path: /spec/glance/template/glanceAPIs/default/replicas
                value: 2

              - op: replace
                path: /spec/cinder/template/cinderAPI/replicas
                value: 2

              - op: replace
                path: /spec/keystone/template/replicas
                value: 2
